spring.application.name=studyhub
spring.datasource.url=jdbc:postgresql://localhost:5432/studyhub
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgrespw
logging.level.org.springframework.security=DEBUG
server.port=8081